### ISSUE TITLE
Camera is a bit laggy sometimes 

### ISSUE THREAD

**Issue by KyleKun** [RafaelBarbosatec/bonfire#352] opened 2022-12-09 02:48 UTC
I am running a release build on Android 12 in a decent phone, and if you keep looking to the house constantly, the camera seems to freeze sometimes for a few milliseconds. The same behavior I noticed on web with canvaskit release build. Any ideas how to improve it with a configuration, or maybe is it really from bonfire side? Thanks!

https://user-images.githubusercontent.com/36611739/206613045-2e5d325a-ee95-47ff-b93c-369564453689.mp4

**Comment by RafaelBarbosatec** [comment] 2022-12-12 12:40
Hi @KyleKun !
Humm, I. will to analyze this problem. I think that it’s caused by high zoom.

**Comment by RafaelBarbosatec** [comment] 2022-12-14 03:11
Doing some tests with a very high zoom, I couldn't find any performance bottleneck, it seems to be a rounding problem or something like that, because it's very close it's visible

**Comment by RafaelBarbosatec** [comment] 2023-08-23 17:45
It's is better in 3.0 version!

**Closed by RafaelBarbosatec** 2023-08-23 17:45 UTC
Labels: bug
